### ISSUE TITLE
Date Picker - Poor performance when showing multiple months with attributes

### ISSUE THREAD

**Issue by nikwins** [nathanreyes/v-calendar#280] opened 2019-03-21 13:47 UTC
Hi @nathanreyes !
First of all I would like you to know that I really like your plugin, it's very intuitive, extendable and easy to work with. So thanks for your work!

I'm usind the v-calendar as it is in the current "dev"-branch (last updated on 19.03.2019) because I really needed the feature to show more than 2 calendar sheets. In my case it's 8 for desktop. 
In my use case I have to show availabilities for every single day (availability of rooms in a hotel). The calendar also has to show events for nearly every single day in a popover and highlight specific date ranges after the user clicks on a filter. 
All this functionality/features works just fine with the big downside that the calendar gets so slow when picking a date range that it can't be navigated properly by the user.

I made a [example page](http://niklas-wingender.de/VCalendarTest/#/) where I just show 8 calendar sheets and only implement 1 attribute (availibility of hotel room) per day. No popovers and now highlighting of specific date ranges. Even then the selection of a date range lasts about 3 seconds which is just extremly slow.

Here is all relevant code:
```
<v-date-picker
    is-inline
    is-expanded
    show-caps
    v-model="calendar.date"
    mode="range"
    :rows="2"
    :columns="4"
    :min-date="new Date()"
    :attributes="calendar.attributes"
    :show-day-popover="false"
    @input="rangeInput"
    class="calendar mt-lg"
>
</v-date-picker>

<script>
export default {
    name: "VCalendarTest",
    data() {
        return {
            calendar: {
                date: null,
                selectedDate: {
                    start: new Date(),
                    end: new Date(),
                },
                attributes: [],
                availablities: [
                    {
                        "Date": "2019-03-21T00:00:00",
                        "ColorCode": "#9fcd69",
                    },
                    // .... 1 attribute per day
                    {
                        "Date": "2019-10-31T00:00:00",
                        "ColorCode": "#9FCD69",
                    }
                ],
            }
        }
    },
    methods: {
        rangeInput(range) {
            this.calendar.selectedDate.start = range.start
            this.calendar.selectedDate.end = range.end
        },
        initCalendarAttributes() {
            var calendarAttributes = []

            // Calendar availability attributes
            var calendarAvailabilites = this.calendar.availablities.map(availability => ({
                key: `availability.${availability.Date}`,
                highlight: {
                    backgroundColor: availability.ColorCode,
                    width: "100%",
                    height: "100%",
                    borderRadius: "0",
                },
                dates: availability.Date,
                customData: availability,
            }))

            // Merge arrays
            calendarAttributes = this.mergeArraysWithoutDuplicates(
                calendarAttributes,
                calendarAvailabilites,
            )

            this.calendar.attributes = calendarAttributes
        },
        mergeArraysWithoutDuplicates(...arr) {
            return [...new Set([].concat(...arr))]
        },
    },
    created() {
        this.initCalendarAttributes()
    }
}
</script>
```

First I tried to implement the attributes through a computed function like it is described in the documentary, but this gives even slower results for big calendars with more than 2 calendar sheets.

My guess is that this is caused by internal bindings and listeners in the plugin itself. So showing that much calendar sheets will just blow the system.
When clicking a date range my CPU usage jumps from 5% to 50% (on an i5 6600).

My question now is:
Is this something you are aware of and have an idea of how to fix this in future updates or didn't you see this problem till now and maybe never planned the calendar to show that much days with attributes?

**Comment by nathanreyes** [comment] 2019-03-21 17:49
If you can, pull the latest changes and run `yarn dev`. Then navigate to 'localhost:8080/tests/` in the browser. I duplicated your example with a few modifications.

There is a slight delay when selecting ranges, but I'd like to add as many attributes as you did to get that effect..maybe see what inefficiency is getting introduced. Could you provide the full list of attributes you are using?

I'm still trying to improving perf for 1.0...for example, you can't define attributes as functions anymore as it was introducing delays and I just don't think it was getting used enough to warrant the penalty.

**Comment by nathanreyes** [comment] 2019-03-22 03:49
So I just checked in a fix for a bug I found when converting the date logic function to an ES6 class. Might give it another shot.

It still doesn't perform as well as I'd like, but it may help your issue.

**Comment by nikwins** [comment] 2019-03-22 12:59
Unfortunately I can't get the test to work. I pulled the latest changes from the dev-branch, but now after compiling, when I open the docs I get this error:
```
[Vue warn]: Error in created hook: "TypeError: Cannot read property 'de' of undefined"
found in
---> <VDatePicker> at src/components/DatePicker.vue
       <VCalendarTest> at docs/.vuepress/components/github/280.vue
         <V98206154> at docs/tests/README.md
           <Content>
             <Page> at node_modules/@vuepress/theme-default/components/Page.vue
               <Layout> at node_modules/@vuepress/theme-default/layouts/Layout.vue
                 <GlobalLayout> at node_modules/@vuepress/core/lib/client/components/GlobalLayout.vue
                   <Root>
```

My default browser language is german, so I changed it to english to see if this solves the problem, but then I get:
```
[Vue warn]: Error in created hook: "TypeError: locales is undefined"
found in
---> <VDatePicker> at src/components/DatePicker.vue
       <VCalendarTest> at docs/.vuepress/components/github/280.vue
         <V98206154> at docs/tests/README.md
           <Content>
             <Page> at node_modules/@vuepress/theme-default/components/Page.vue
               <Layout> at node_modules/@vuepress/theme-default/layouts/Layout.vue
                 <GlobalLayout> at node_modules/@vuepress/core/lib/client/components/GlobalLayout.vue
                   <Root>
```

I now extended my [example page](http://niklas-wingender.de/VCalendarTest/#/) with events that are shown in popovers.
Following code samples have changed:
Data object:
```
    data() {
        return {
            calendar: {
                date: null,
                selectedDate: {
                    start: new Date(),
                    end: new Date(),
                },
                attributes: [],
                availablities: [
                    // availablities from linked json
                ],
                events: [
                    // events from linked json
                ]
            }
        }
    },
```
initCalendarAttributes method:
```
        initCalendarAttributes() {
            var calendarAttributes = []

            // Calendar availability attributes
            var calendarAvailabilites = this.calendar.availablities.map(availability => ({
                key: `availability.${availability.Date}`,
                highlight: {
                    backgroundColor: availability.ColorCode,
                    width: "100%",
                    height: "100%",
                    borderRadius: "0",
                },
                dates: availability.Date,
                customData: availability,
            }))

            // Calendar event attributes
            var calendarEvents = this.calendar.events.map(event => ({
                key: `event.${event.id}`,
                popover: {
                    label: event.title
                },
                dates: this.getEventRange(event.startDate, event.endDate),
                customData: event,
            }))

            // Merge arrays
            calendarAttributes = this.mergeArraysWithoutDuplicates(
                calendarAttributes,
                calendarEvents,
                calendarAvailabilites,
            )

            this.calendar.attributes = calendarAttributes
        },
```
New method to return event ranges in an array:
```
        getEventRange(startDate, endDate) {
            var dates = [startDate, endDate]

            var currDate = this.$moment(startDate).startOf("day")
            var lastDate = this.$moment(endDate).startOf("day")

            while (currDate.add(1, "days").diff(lastDate) < 0) {
                dates.push(currDate.clone().toDate())
            }

            return dates
        },
```

I made a json for the [availability attributes](http://niklas-wingender.de/availabilites.json) and the [event attributes](http://niklas-wingender.de/events.json) so that you have the exact same data as me and I don't have to overstuff the code part in this issue.

**Comment by nikwins** [comment] 2019-04-01 12:56
@nathanreyes Any updates on this?

**Comment by nathanreyes** [comment] 2019-04-10 18:11
The v1 beta is now uploaded to npm so you can install it using the **next** branch.

```bash
npm i --save v-calendar@next
```
That should include the latest bug fixes I made. I'm going to try to focus on perf improvements before moving it out of beta so please advise if you are still having issues.

**Comment by nikwins** [comment] 2019-04-12 10:38
@nathanreyes I've pulled the latest changes from v-calendar@1.0.0-beta.4 and have seen you made a lot of changes which makes some of the code i posted above regarding the styling of attributes obsolete. But the performance issues still persist. The selection of a date range lasts about ~2-3 seconds which is alot more than can be tolerated in production. Have you tried it yourself using the [availability attributes](http://niklas-wingender.de/availabilites.json) and [event attributes](http://niklas-wingender.de/events.json) I've provided?

**Comment by nathanreyes** [comment] 2019-04-12 21:44
Yes it seems I may need to reconsider how date matches are resolved to account for multi-paned calendars. The issue is exponential based on the number of panes.

**Comment by nathanreyes** [comment] 2019-04-18 21:11
Ok so Beta 5 includes some pretty significant performance improvements. I loaded a [modified](https://github.com/nathanreyes/v-calendar/blob/next/docs/github/280.vue) version of your example which you can [try out here](https://vcalendar.io/github/280).

Thanks for reporting. This was something that needed to get done.

**Comment by nikwins** [comment] 2019-04-23 12:42
Yes that's it! That was the performance boost it needed. 
Thanks a lot for your efforts, really appreciating your work! 
Glad I could help :)

**Closed** 2019-05-13 13:41 UTC
Labels: bug

**Comment by CTHOK** [comment] 2024-08-20 02:10
Hi, currently i integrate to my source code. But the UI display one month in  calendar only. Anyone can guide which part i need to check ?

<v-date-picker
        is-inline
        no-title
    is-expanded
    show-caps
    v-model="calendar.date"
    mode="range"
    :rows="1"
    :columns="2"
    :min-date="new Date()"
    :attributes="calendar.attributes"
    :show-day-popover="false"
    @input="rangeInput"
    class="calendar mt-lg"
        >

      </v-date-picker>
