### ISSUE TITLE
Cannot use minDate/maxDate along with available dates.

### ISSUE THREAD

**Issue by dexcell** [nathanreyes/v-calendar#570] opened 2020-05-02 12:41 UTC
From the documentation

> Use the min-date, min-page, max-date or max-page props to manually assign the page bounds when using disabled-dates or available-dates.

**Actual result:** (v1.0.6)
`available-dates` gets ignored when `min-date` or `max-date` set.

Happened on both v-calendar and v-date-picker.
Here is how initiate my calendar.
````
<v-date-picker     
    v-model="calendarSelectedDate"
    is-inline    
    :min-date="calendarMinDate"
    :max-date="calendarMaxDate"
    :available-dates="availableDates"
></v-date-picker>
````

**Expected result:**
`available-dates` plays along with `min-date` or `max-date` set.

**Comment by tafelnl** [comment] 2020-05-27 08:44
Duplicate of: https://github.com/nathanreyes/v-calendar/issues/203

With this being a workaround: https://github.com/nathanreyes/v-calendar/issues/203#issuecomment-634024061

**Comment by nathanreyes** [comment] 2021-01-25 21:33
Since `min-date` and `max-date` are both used, we don't get an implicit infinite disabled range to override with `available-dates`, so we have to add it explicitly.

This writeup might help too. https://vcalendar.io/disable-dates.html#simultaneous-use

```html
  <v-date-picker
    v-model="date"
    :min-date="minDate"
    :max-date="maxDate"
    :disabled-dates="disabledDates"
    :available-dates="availableDates"
  />
```
```js
export default {
  data() {
    return {
      date: null,
      minDate: new Date(2021, 0, 4),
      maxDate: new Date(2021, 2, 19),
      disabledDates: { },
      availableDates: [
        { start: new Date(2021, 1, 9), end: new Date(2021, 1, 19) },
      ],
    };
  },
};
```

**Closed by nathanreyes** 2021-01-25 21:33 UTC
