### ISSUE TITLE
Datepicker input event triggered on load

### ISSUE THREAD

**Issue by sigjak** [nathanreyes/v-calendar#619] opened 2020-06-26 20:54 UTC
I have been using the **input event** to run a function in datepicker (range mode) after selecting the range. In versions prior to 1.07 the input event was trigger on selecting a range. In versions 1.07 and 1.08 the input event is triggered on initial load prior to any selection being made.  If this is the intended behavior (ie. not a bug) is it possible to change this behavior in the latest versions and prevent the input event from triggering on initial load?
 Any suggestion would be much appreciated.!

**Comment by sigjak** [comment] 2020-06-28 13:34
It would be nice to know if this is a **bug** or  if this is indeed the preferred behavior. It seems strange to trigger the input event before the user has any possibility of interacting with the calendar.

**Comment by swash13** [comment] 2020-07-08 16:00
same here. Tried everything, but ended up just checking dates for equality. Not sure what other solutions are possible ?

**Comment by josecurioso** [comment] 2020-07-09 10:31
Same here, I don't think it should be an intended behavior since no input is made.

**Comment by sigjak** [comment] 2020-07-09 11:23
My way around this was to create a variable called **firstRun** and set it initially to true. When the datepicker loads  it calls a function @input =”doSomething” which handles my input logic. If **firstRun is true** it sets **firstRun to false** and returns doing nothing. On next call from the @input, the doSomething function does what I want it to do and the new input behaviour is ignored.

**Comment by nathanreyes** [comment] 2021-01-25 20:29
For `2.0` and later (haven't tested all the later `1.0` versions), this should be fixed.

**Closed by nathanreyes** 2021-01-25 20:29 UTC
Labels: bug
