### ISSUE TITLE
availalbe-dates is not gray out

### ISSUE THREAD

**Issue by duckytutu** [nathanreyes/v-calendar#326] opened 2019-05-29 04:17 UTC
Im updating `available-dates` on `dayclick` event. But the available dates is updated but the disabled date is not gray out. I cannot select the date is disabled but their styles are not match

![image](https://user-images.githubusercontent.com/14825696/58528979-1deb8d80-8203-11e9-850f-3f5708adc853.png)
This is when i click

![image](https://user-images.githubusercontent.com/14825696/58529007-3d82b600-8203-11e9-8685-3508cd883324.png)
And this is when i move to next page then back

**Comment by nathanreyes** [comment] 2019-06-01 15:25
Dupe of #323 which is going to get patched in the next beta.

**Comment by dewdad** [comment] 2019-06-02 06:40
I'm not sure that this is a dupe of #323. It seems that the **available-dates** attribute just doesn't get recomputed on changes to **attributes**. This causes an inconsistency when **attributes** and **available-dates** are computed from the same state. I have a demo of it running [here](https://dewdad.github.io/demos/#/calendar) and the [code](https://github.com/dewdad/demos/blob/vue-cli/src/pages/calendar.vue)

**Comment by nathanreyes** [comment] 2019-06-02 19:04
I believe beta.14 should fix this but I can't retest until later today or tomorrow. Might want to check it out though.

**Comment by dewdad** [comment] 2019-06-07 19:31
Fixed! Thank you

**Closed** 2019-06-21 08:27 UTC
Labels: bug, next-release
