### ISSUE TITLE
TypeError: Cannot read property 'select' of undefined

### ISSUE THREAD

**Issue by amadoalmex** [nathanreyes/v-calendar#171] opened 2018-07-06 16:23 UTC
I have version 0.9.7 and I am getting a JS Type Error:
Can someone tell me if I need to provide some extra parameter or how I can avoid getting this error? Thanks

My Code:
![selection_999 040](https://user-images.githubusercontent.com/31776001/42389565-c45e02c0-810e-11e8-8108-4e7ab710b725.png)

Error:
![selection_999 038](https://user-images.githubusercontent.com/31776001/42389572-caa1259a-810e-11e8-9d34-da1e2a663d12.png)

Narrowed it down to this source file:
https://github.com/nathanreyes/v-calendar/blob/b4c2ca0804d651e9f01cf25b8c1c8c02ca35eaf6/src/components/CalendarDayPopoverRow.vue#L29

Edit, error is triggered when I select a date on the calendar.

**Comment by kl3sk** [comment] 2018-08-03 08:25
I'll try to do a fiddle with these informations, and can't reproduce your issue.

here is the fiddle: https://jsfiddle.net/klesk/szL0ek61/


Maybe provide more code or complete the fiddle with your parameters I don't have.

**Comment by nathanreyes** [comment] 2021-01-13 00:22
Closing outstanding issue. Please generate new issue if needed (preferably with example link).

**Closed by nathanreyes** 2021-01-13 00:22 UTC
