### ISSUE TITLE
Disable specific days of the week

### ISSUE THREAD

**Issue by cdmoro** [nathanreyes/v-calendar#12] opened 2017-11-19 04:58 UTC
Possibility to disable specific days of the week. Par exemple, disable choosing Sathurdays and Sundays

**Comment by nathanreyes** [comment] 2017-11-19 16:08
Duplicate of #7

**Comment by cdmoro** [comment] 2017-11-19 16:21
I think this issue and the #7 are slightly differentes, the #7 it's about apply a style to specific days, this issue is about make certains days unselectable by the user. Par exemple, the datepicker of this site https://wffranco.github.io/vue-strap/#datepicker

**Comment by nathanreyes** [comment] 2017-12-11 15:37
In 0.4.0, you can use date patterns with the `disabled-dates` prop. So, for your example, you can use the following notation:
```html
<v-date-picker
  :disabled-dates='disabledDates'>
</v-date-picker>
```
```javascript
export default {
  data() {
    return {
      disabledDates: { weekdays: [1, 7] },
    };
  }
}
```
For more information about date patters, you can reference the [README](https://github.com/nathanreyes/v-calendar/blob/master/README.md) for more info about date patterns, as the documentation has not yet been updated to explain them fully. Also, the [website](https://vcalendar.netlify.com) uses this very example for the date picker demo.

**Comment by vinkodlak** [comment] 2017-12-15 00:24
Nathan, really great work, thank you!

Can we distinguish between disabled dates and, hm, 'unselectable' dates. For example, if sat and sun are unselectable, you could still pick friday until monday, but if some dates are disabled you could not select after those?

**Comment by nathanreyes** [comment] 2017-12-15 02:02
Yes, what you describe is how it should work. I just forgot to fully test this in trying to finish up the last feature.

**Closed** 2018-01-10 20:38 UTC
Labels: enhancement, next-release

**Comment by jayheavner** [comment] 2020-04-08 20:35
I know this is very old but has the unselectable vs disabled been resolved? I'm trying to do a work scheduler and Sat/Sun are unselectable but things can certainly span over weekends.
