### ISSUE TITLE
NaN/NaN/0NaN when entering Alphabetical Chars in the input field

### ISSUE THREAD

**Issue by PatrickJunod** [nathanreyes/v-calendar#1283] opened 2023-03-24 22:45 UTC
## What it is

When entering letters or something that is not a number in the attached V-Calendar input field, the field is showing the following input: "NaN/NaN/0NaN"

<img width="448" alt="image" src="https://user-images.githubusercontent.com/29105077/227656303-b5cf8821-425f-445a-9096-adc1c50d67b6.png">

## What it should be
It should simply remove the text and make the input "null".

## How to reproduce
Go here: https://vcalendar.io/examples/date-picker-popovers.html
Write some alphabetic chars and press tab to loose focus on the date picker input

## System

V-Calendar V.3.0.1
Mac OS
Chrome
CH (fr-FR)

Thanks a lot,
Best regards

**Comment by nathanreyes** [comment] 2023-03-25 05:30
Duplicate of #1270.

**Comment by nathanreyes** [comment] 2023-03-26 20:10
Fixed in 3.0.2

**Closed by nathanreyes** 2023-03-26 20:10 UTC
Labels: bug
