### ISSUE TITLE
Excelente

### ISSUE THREAD

**Issue by nam-co** [nathanreyes/v-calendar#331] opened 2019-06-01 15:32 UTC
Congrats on this Nathan, I was wondering if is possible to add custom buttons on the bottom? It would be cool if it allow for example “today” and “my birthday” buttons, where you specify on the script buttons: {"today":new Date(),"My Birthday":xxxxx} , a simple bg->light, text->white button

Just an idea
Thanks for everything

**Comment by nathanreyes** [comment] 2019-06-01 17:39
Dupe of #316?

**Comment by ianbunn** [comment] 2020-04-20 15:11
Hi @nam-co were you able to add the buttons in the footer? If so, would you mind guiding me as to how you accomplished that? Did you maybe use some type of custom navigation button mentioned here https://vcalendar.io/navigation.html#move-to-a-date?

How were you able to include the button in the actual datepicker component?

Thanks for your time!

**Comment by nam-co** [comment] 2020-04-20 15:46
Hi @ianbunn I completely forgot about this, I never continue with the idea, sorry

**Comment by nathanreyes** [comment] 2021-01-16 01:21
Apologies for late reply. There has since been added a `footer` slot for this purpose.
https://vcalendar.io/changelog/v2.0.html#_2-use-footer-scoped-slot

**Closed by nathanreyes** 2021-01-16 01:21 UTC
Labels: enhancement
