### ISSUE TITLE
Doesn't work with Vue 3

### ISSUE THREAD

**Issue by martinszeltins** [nathanreyes/v-calendar#716] opened 2020-11-19 07:19 UTC
When using with Vue 3 it shows an error

> Uncaught TypeError: a.a.mixin is not a function

**Reproducion code**

```html
<html>
  <body>
    <div id='app'>
      <v-calendar></v-calendar>
      <v-date-picker v-model='selectedDate' />
    </div>

    <script src="https://unpkg.com/vue@next"></script>
    <script src='https://unpkg.com/v-calendar'></script>

    <script>  
        const App = {
            data() {
                return {
                    selectedDate: null,
                }
            }
        }

        Vue.createApp(App).mount('#app')
    </script>
  </body>
</html>
```

**Comment by MariusRumpf** [comment] 2020-11-19 07:59
This is a duplicate of #633

**Comment by nathanreyes** [comment] 2020-12-14 03:40
Please use the `next` branch to try out Vue 3 compatible version.

`npm i -S v-calendar@next`

**Closed by nathanreyes** 2020-12-14 03:40 UTC
